inputs_def:
  - handle: image_url
    json_schema:
      type: string
    nullable: false
  - handle: output_file
    json_schema:
      type: string
      ui:widget: save
    value:
    nullable: true
outputs_def:
  - handle: image
    json_schema:
      type: string
      contentMediaType: oomol/file

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "Background Remove"
description: Enter a picture address, remove the background, and output an address
icon: ":carbon:image:"
